In [1]:
import csv

In [5]:
with open("movies.csv") as file:
    data = list(csv.reader(file))
    print(data[1])

['Pather Panchali', 'Bollywood', '1955', '8.3', 'Government of West Bengal', '70000', '100000', 'Thousands', 'INR', 'Bengali']

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("movies.csv")

In [3]:
print(df)

                                          title   industry  release_year  \
0                               Pather Panchali  Bollywood          1955
1   Doctor Strange in the Multiverse of Madness  Hollywood          2022
2                         Thor: The Dark World   Hollywood          2013
3                               Thor: Ragnarok   Hollywood          2017
4                       Thor: Love and Thunder   Hollywood          2022
5                      The Shawshank Redemption  Hollywood          1994
6                                  Interstellar  Hollywood          2014
7                      The Pursuit of Happyness  Hollywood          2006
8                                     Gladiator  Hollywood          2000
9                                       Titanic  Hollywood          1997
10                        It's a Wonderful Life  Hollywood          1946
11                                       Avatar  Hollywood          2009
12                                The Godfather  Hollywood          1972
13                              The Dark Knight  Hollywood          2008
14                             Schindler's List  Hollywood          1993
15                                Jurassic Park  Hollywood          1993
16                                     Parasite  Hollywood          2019
17                            Avengers: Endgame  Hollywood          2019
18                       Avengers: Infinity War  Hollywood          2018
19           Captain America: The First Avenger  Hollywood          2011
20          Captain America: The Winter Soldier  Hollywood          2014
21                  Dilwale Dulhania Le Jayenge  Bollywood          1995
22                                     3 Idiots  Bollywood          2009
23                     Kabhi Khushi Kabhie Gham  Bollywood          2001
24                             Bajirao Mastani   Bollywood          2015
25                             Taare Zameen Par  Bollywood          2007
26                          Munna Bhai M.B.B.S.  Bollywood          2003
27                                           PK  Bollywood          2014
28                                        Sanju  Bollywood          2018
29                            The Kashmir Files  Bollywood          2022
30                            Bajrangi Bhaijaan  Bollywood          2015
31                                       Race 3  Bollywood          2018
32                                    Shershaah  Bollywood          2021
33                             K.G.F: Chapter 2  Bollywood          2022
34                    Pushpa: The Rise - Part 1  Bollywood          2021
35                                          RRR  Bollywood          2022
36                     Baahubali: The Beginning  Bollywood          2015

    imdb_rating                     studio    budget   revenue       unit  \
0           8.3  Government of West Bengal  70000.00  100000.0  Thousands
1           7.0             Marvel Studios    200.00     954.8   Millions
2           6.8             Marvel Studios    165.00     644.8   Millions
3           7.9             Marvel Studios    180.00     854.0   Millions
4           6.8             Marvel Studios    250.00     670.0   Millions
5           9.3  Castle Rock Entertainment     25.00      73.3   Millions
6           8.6      Warner Bros. Pictures    165.00     701.8   Millions
7           8.0          Columbia Pictures     55.00     307.1   Millions
8           8.5       Universal Pictures      103.00     460.5   Millions
9           7.9         Paramount Pictures    200.00    2202.0   Millions
10          8.6              Liberty Films      3.18       3.3   Millions
11          7.8           20th Century Fox    237.00    2847.0   Millions
12          9.2         Paramount Pictures      7.20     291.0   Millions
13          9.0                    Syncopy    185.00    1006.0   Millions
14          9.0         Universal Pictures     22.00     322.2   Millions
15          8.2         Universal Pictures     63.00    1046.0   Millions
16          8.5                        NaN     15.50     263.1   Millions
17          8.4             Marvel Studios    400.00    2798.0   Millions
18          8.4             Marvel Studios    400.00    2048.0   Millions
19          6.9             Marvel Studios    216.70     370.6   Millions
20          7.8             Marvel Studios    177.00     714.4   Millions
21          8.0             Yash Raj Films    400.00    2000.0   Millions
22          8.4         Vinod Chopra Films    550.00    4000.0   Millions
23          7.4         Dharma Productions    390.00    1360.0   Millions
24          7.2                        NaN      1.40       3.5   Billions
25          8.3                        NaN    120.00    1350.0   Millions
26          8.1   Vinod Chopra Productions    100.00     410.0   Millions
27          8.1         Vinod Chopra Films    850.00    8540.0   Millions
28          NaN         Vinod Chopra Films      1.00       5.9   Billions
29          8.3                Zee Studios    250.00    3409.0   Millions
30          8.1          Salman Khan Films    900.00   11690.0   Millions
31          1.9          Salman Khan Films      1.80       3.1   Billions
32          8.4         Dharma Productions    500.00     950.0   Millions
33          8.4              Hombale Films      1.00      12.5   Billions
34          7.6        Mythri Movie Makers      2.00       3.6   Billions
35          8.0          DVV Entertainment      5.50      12.0   Billions
36          8.0           Arka Media Works      1.80       6.5   Billions

   currency language
0       INR  Bengali
1       USD  English
2       USD  English
3       USD  English
4       USD  English
5       USD  English
6       USD  English
7       USD  English
8       USD  English
9       USD  English
10      USD  English
11      USD  English
12      USD  English
13      USD  English
14      USD  English
15      USD  English
16      USD  English
17      USD  English
18      USD  English
19      USD  English
20      USD  English
21      INR    Hindi
22      INR    Hindi
23      INR    Hindi
24      INR    Hindi
25      INR    Hindi
26      INR    Hindi
27      INR    Hindi
28      INR    Hindi
29      INR    Hindi
30      INR    Hindi
31      INR    Hindi
32      INR    Hindi
33      INR  Kannada
34      INR   Telugu
35      INR   Telugu
36      INR   Telugu

In [4]:
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu

In [5]:
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [6]:
df.head(3)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English

In [7]:
df.tail()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [8]:
df[2:3]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English

In [9]:
df[3:6]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [10]:
df.shape()

TypeError: 'tuple' object is not callable

In [11]:
df.shape

(37, 10)

In [17]:
dir(df.title)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_cacher',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_convert_dtypes',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_expanddim_from_mgr',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [18]:
df.shape

(37, 10)

In [19]:
df.imdb_rating.min(),df.imdb_rating.max()

(1.9, 9.3)

In [20]:
df.imdb_rating.mean(),

(7.919444444444445,)

In [21]:
df.release_year

0     1955
1     2022
2     2013
3     2017
4     2022
5     1994
6     2014
7     2006
8     2000
9     1997
10    1946
11    2009
12    1972
13    2008
14    1993
15    1993
16    2019
17    2019
18    2018
19    2011
20    2014
21    1995
22    2009
23    2001
24    2015
25    2007
26    2003
27    2014
28    2018
29    2022
30    2015
31    2018
32    2021
33    2022
34    2021
35    2022
36    2015
Name: release_year, dtype: int64

In [40]:
releaseyr_2022 = df[df.release_year==2022]

In [41]:
releaseyr_2022

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.0,3409.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu

In [46]:
hollywood_df = df[df.industry=="Hollywood"]
bollywood_df = df[df.industry=="Bollywood"]

In [58]:
bollywood_df = df[df.industry=="Bollywood"]
bollywood_df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.0,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.4,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.0,8540.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.0,3409.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.0,11690.0,Millions,INR,Hindi
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [50]:
hollywood_df.imdb_rating.min(),hollywood_df.imdb_rating.max(),hollywood_df.imdb_rating.mean(),

(6.8, 9.3, 8.130000000000003)

In [59]:
bollywood_df.imdb_rating.min(),bollywood_df.imdb_rating.max(),bollywood_df.imdb_rating.mean(),

(1.9, 8.4, 7.656250000000001)